
services:
  itp-server-db:
    image: postgres:16.3-bullseye
    container_name: itp-server-db
    ports:
      - "4242:5432"
    environment:
      POSTGRES_PASSWORD: itp123
      POSTGRES_USER: itp-admin
      POSTGRES_DB: itp-server-db
    volumes:
      - itp-service-vol:/var/lib/postgresql/data

# Create Docker Volume and Network
volumes:
  itp-service-vol:
networks:
  itp-net: