spring:
  application:
        name: ITP-identity-service
  datasource:
    url: jdbc:postgresql://localhost:4242/itp-server-db
    username: itp-admin
    password: itp123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
      port: 9999
